{{- if .Values.networkPolicies.enabled }}
# TODO add trusted namespace/pod policies
{{- if .Values.networkPolicies.installBaseline }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: baseline-default-no-ingress-egress
  namespace: {{ .Values.tenantName . }}
  labels:
    {{- include "basic-tenant.labels" . | nindent 4 }}
    tenant: {{ .Values.tenantName . }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: baseline-allow-same-ns
  namespace: {{ .Values.tenantName . }}
  labels:
    {{- include "basic-tenant.labels" . | nindent 4 }}
    tenant: {{ .Values.tenantName . }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - podSelector: {}
{{- end }}
{{- range .Values.networkPolicies.extraNetworkPolicies }}
---
{{ include "common.tplvalues.render" (dict "value" . "context" $) }}
{{- end }}
{{- end }}
