# This is a basic workflow to help you get started with Actions

name: Basic-tenant

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, dev ]
    paths:
      - 'basic-tenant/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'basic-tenant/**'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# From https://github.com/helm/chart-testing-action
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        working-directory: basic-tenant
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        working-directory: basic-tenant
        run: ct lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        working-directory: basic-tenant
        run: ct install